
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const LOGGED_OUT = 'LOGGED_OUT';

export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const AUTH_LOADING = 'AUTH_LOADING';

export const USER_Token = 'USER_Token';

const authActionTypes = {
    //AUTH ACTION TYPES
    SET_AUTHENTICATED : 'SET_AUTHENTICATED',
    LOGGED_OUT : 'LOGGED_OUT',

    SET_AUTH_ERROR : 'SET_AUTH_ERROR',
    AUTH_LOADING : 'AUTH_LOADING',

    // USER LOGIN ACTION TYPES
    EMAIL_LOGIN_START: "EMAIL_LOGIN_START",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    //USER REGISTER ACTION TYPES
    EMAIL_REGISTER_START: "EMAIL_REGISTER_START",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",

    //USER SIGNOUT ACTIONS
    SIGN_OUT_START: "SIGN_OUT_START",
    SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
    SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",

    //set current user
    SET_USER_TOKEN: "SET_USER_TOKEN",
    SET_CURRENT_USER: "SET_CURRENT_USER",

    //Clear login or signup errors
    CLEAR_USER_ERROR: "CLEAR_USER_ERROR",

    //USER fetch ACTIONS
    USER_FETCH_START: "USER_FETCH_START",
    USER_FETCH_SUCCESS: "USER_FETCH_SUCCESS",
    USER_FETCH_FAILURE: "USER_FETCH_FAILURE",
};

export default authActionTypes;